query InvalidFriendsOfFriends($page:Int!, $size:Int!) {
    user {
        friends(page: $page, size: $size) {
            edges {
                node {
                    friends(page: $page, size: $size) {
                        edges {
                            node {
                                friends(page: $page, size: $size) {
                                    edges {
                                        node {
                                            username
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

query FriendsOfFriends($page:Int!, $size:Int!) {
    user {
        friends(page: $page, size: $size) {
            edges {
                node {
                    friends(page: $page, size: $size) {
                        edges {
                            node {
                                id
                                username
                            }
                        }
                    }
                }
            }
        }
    }
}
